# Generated by Django 5.1.3 on 2024-12-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=12, unique=True)),
                ('aadhar', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='Images')),
                ('mobile', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('balance', models.FloatField(default=5000.0)),
                ('pin', models.CharField(default=0, max_length=20)),
                ('address', models.TextField()),
                ('otp', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
